# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty


# Setup
title:            Hyde12341234
tagline:          '123414A Jekyll theme'
description:      '34563A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://hyde.getpoole.com
baseurl:          '/hyde/'

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         0 #changed

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
